COMPILER=g++

HEADER_FILES=
INCLUDE_DIRECTORIES=include

SOURCE_FILES=src/main.cpp

OUTPUT_DIR=install/
OUTPUT_NAME=test

all:
	$(COMPILER) -I $(INCLUDE_DIRECTORIES) $(SOURCE_FILES) -o $(OUTPUT_DIR)$(OUTPUT_NAME)